name: Transactional Multi-Job Test

on: [push, workflow_dispatch]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./action/start
        with:
          spec: tx.yaml

  step1:
    needs: start
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./action/step
        with:
          id: step-1
          run: echo "Step 1 executing"
          compensate: echo "Rolling back step 1"

  step2:
    needs: step1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./action/step
        with:
          id: step-2
          run: exit 1  # Fails intentionally to trigger rollback
          compensate: echo "Rolling back step 2"

  end:
    needs: [start, step1, step2]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./action/end

